version: '3.7'
services:
  db:
    image: postgres:12.2
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  # web:
  #   build: .
  #   command: bash -c "npm run db-create && npm run postinstall && npm run db-seed && npm run dev"
  #   volumes:
  #     - .:/usr/src/app
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - db
  #   environment:
  #     - DATABASE_URL=postgres://user:password@db:5432/db?schema=newsbits
  #     - NODE_ENV=development
