version: '3.7'
services:
  db:
    image: postgres:12.2
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    build: .
    command: bash -c "yarn db-prep && yarn dev"
    volumes:
      # mount everything except node_modules
      - .:/usr/src/app
      # mount node_modules from a volume to avoid permission issues
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/db?schema=techstories
      - NODE_ENV=development
